name: amoz_customer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.19.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/service_booking/
    - assets/service_booking/maps/
    - assets/rent_vehicle/icons/
    - assets/rent_vehicle/cars/
    - assets/rent_vehicle/banners/
    - assets/rent_vehicle/features/
    - assets/rent_vehicle/addons/
    - assets/rent_vehicle/payment/
    - assets/rent_vehicle/success/
    - assets/my_orders/
    - assets/quick_trigger/
    - assets/orders/cancel_order/
    - assets/orders/track_invoice/
    - assets/profile/
    - assets/settings/
    - assets/wallet/
    - assets/coupons_loyalty/
    - assets/notifications/
    - assets/documents/
    - assets/search/
    - assets/blank_states/
    - assets/support_chat/
    - assets/subscriptions/
    - assets/subscriptions/sports/
    - assets/subscriptions/turf/
    - assets/subscriptions/salon/
    - assets/translations/