name: amoz_customer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.20.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  permission_handler: ^11.3.1
  carousel_slider: ^5.0.0
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/service_booking/
    - assets/service_booking/maps/
    - assets/rent_vehicle/cars/
    - assets/rent_vehicle/banners/
    - assets/rent_vehicle/addons/
    - assets/rent_vehicle/success/
    - assets/my_orders/
    - assets/quick_trigger/
    - assets/orders/cancel_order/
    - assets/profile/
    - assets/notifications/
    - assets/search/
    - assets/blank_states/
    - assets/support_chat/
    - assets/translations/